### ISSUE TITLE
Add info about packages' CPU architecture support

### ISSUE THREAD

**Issue by emiliofernandes** [bioconda/bioconda-docs#34]
Hi,

Would it be possible to add information about which CPU architectures are supported by each package/recipe at https://bioconda.github.io/conda-package_index.html ?

At the moment I could get this info from the `meta.yaml` of a recipe and/or find the package at https://anaconda.org, but this is only one by one.
For me it would be really useful if I can see and filter this information at the page that lists all Bioconda packages.

**Comment by martin-g** [comment]
I like the idea!
The best would be https://anaconda.org/ to provide UI controls for filtering by channel (e.g. `bioconda`) and by CPU architecture. But I have no idea who to convince about improving https://anaconda.org/
I'll take a look how to add this information to [conda-package_index.html](https://bioconda.github.io/conda-package_index.html)!

**Comment by martin-g** [comment]
@ Anyone more familiar with this repo: Where `otherdata['objects']` is populated ?
https://github.com/bioconda/bioconda-docs/blob/5021bc45b1d26e35082777ce2a532f2941da823a/source/_ext/bioconda_sphinx_ext.py#L508

https://github.com/bioconda/bioconda-docs/blob/5021bc45b1d26e35082777ce2a532f2941da823a/source/_ext/bioconda_sphinx_ext.py#L398 uses this data to prepare it for rendering, but I cannot find the code that initializes `otherdata['objects']`

**Comment by martin-g** [comment]
This issue could be closed!
#36 has been merged.
